"""LangGraph state schema for the ETL pipeline graph."""

from __future__ import annotations

from typing import Any, Optional
from typing_extensions import TypedDict


class GapItem(TypedDict):
    """A single schema gap between source and unified schema."""
    target_column: str
    target_type: str
    source_column: Optional[str]  # None if column must be derived
    source_type: Optional[str]
    action: str  # MAP, DROP, NEW, ADD
    sample_values: list[str]


class GeneratedFunction(TypedDict):
    """A function generated by Agent 2."""
    function_name: str
    function_code: str
    file_path: str  # path in function_registry/functions/
    registry_key: str
    validation_passed: bool
    sample_outputs: dict


class PipelineState(TypedDict, total=False):
    """
    Full state flowing through the LangGraph pipeline.

    total=False allows nodes to set fields incrementally —
    not every field is present at every node.
    """
    # Input
    source_path: str
    source_df: Any  # pd.DataFrame — not JSON-serializable, in-memory only
    source_schema: dict  # column_name -> {dtype, null_rate, sample_values}
    domain: str  # "nutrition", "safety", "pricing"

    # Schema analysis (set by orchestrator node)
    unified_schema: dict
    unified_schema_existed: bool  # True if schema was loaded, False if derived
    gaps: list[GapItem]
    column_mapping: dict  # source_col -> unified_col

    # Registry results (set by registry_check node)
    registry_hits: dict  # gap_key -> function file path
    registry_misses: list[GapItem]

    # Code generation results (set by code_generator node)
    generated_functions: list[GeneratedFunction]
    retry_count: int
    max_retries: int

    # Pipeline execution
    block_sequence: list[str]
    working_df: Any  # pd.DataFrame
    dq_score_pre: float
    dq_score_post: float

    # Enrichment
    enrichment_stats: dict  # tier -> row_count

    # Quarantine
    quarantined_df: Any  # pd.DataFrame — rows that failed post-enrichment validation
    quarantine_reasons: list[dict]  # [{row_idx, missing_fields, reason}]

    # Audit
    audit_log: list[dict]
    errors: list[str]
